version: "3"

services:
  drug_search:
    image: drug_search:1.2.0
    container_name: drug_search
    restart: always
    ports:
      - "1999:1999"
    network_mode: host
    volumes:
      - "/etc/timezone:/etc/timezone:ro"
      - "/etc/localtime:/etc/localtime:ro"
#    networks:
#      - drug_service

#networks:
#    drug_service:
#      driver: bridge 
    
